### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#110]
* [x] Flight Planning  #111 
* [x] Procurement  #115 
* [x] Flight Computer Smoke Test #112 
* [x] Control Camera Smoke Test 
* [x] Backup GPS Tracker Smoke Test
* [x] GND Preparations
* [ ] Ground Station Arrangements
* [x] Avionics Integration (Service Module)
* [x] TOMI Integration
* [x] Control Camera Integration
* [x] Payload Integration
* [x] Full System Integration
