### ISSUE TITLE
Flight Planning TDM-7

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#116]
* [x] Designate launch date
* [x] Clarify Objectives
* [ ] Clarify Roles
* [ ] GANTT
* [x] Notify local FAA
* [ ] Callsign Arrangements
* [ ] Remote Sensing Legal Issues
* [ ] Update Checklists
* * [ ] Flight Computer Integration
* * [ ] Avionics Integration
* * [ ] Payload Integration
* * [ ] Control Camera Integration
* * [ ] TOMI Integration
* * [ ] Launch (Platform)
* * [ ] Launch (Payload)
* * [ ] Launch Equipment
* * [ ] GND Equipment
* * [ ] Recovery Equipment
* [ ] Run Predictions #124 
* [ ] Recovery Team Plans

**Comment by Bgoczan** [comment]
Launch notice for the Hungarian FAA

[TDM-7_launch_notice_i0.1.pdf](https://github.com/legokor/UPRA-Flights/files/8103348/TDM-7_launch_notice_i0.1.pdf)

**Comment by Bgoczan** [comment]
Launch notice sent for the Hungarian FAA
[TDM-7_launch_notice_i1.0.pdf](https://github.com/legokor/UPRA-Flights/files/8103723/TDM-7_launch_notice_i1.0.pdf)
