### ISSUE TITLE
Flight Preparation TDM-7

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#122]
* [ ] Flight Planning  #116 
* [ ] Procurement  #117
* [ ] Flight Computer Smoke Test #118 
* [ ] Control Camera Smoke Test 
* [ ] Backup GPS Tracker Smoke Test
* [ ] GND Preparations
* [ ] Ground Station Arrangements #123 
* [ ] Payload Development #119
* [ ] Avionics Integration (Service Module)
* [ ] TOMI Integration
* [ ] Control Camera Integration
* [ ] Payload Integration
* [ ] Full System Integration
