### ISSUE TITLE
Flight Preparation

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#18]
* [x] Apply 'Lessons Learned' from the previous flight #19 
* [x] ~~Temperature Sensor Calibration #20~~
* [x] Add Altitude information to APRS packet #21 
* [x] Pre-flight Smoke Tests #22 
* [x] ~~Parachute Test (optional/good to have) #23~~
* [x] Service Module Integration #24 
* [x] Payload preparation #25 #26 
* [x] Payload Integration #27 
* [x] Flight Simulation 
* [x] Official Notice to local FAA
* [x] Recovery Plan
* [x] Prepare launch equipment
