### ISSUE TITLE
Flight Preparation

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#30]
## [GANT](https://github.com/legokor/UPRA-Flights/blob/master/MATeF-4/Flight_Planning/MATeF-4_gant.pdf)

* [x] Apply 'Lessons Learned' from the previous flight  #33 
* [x] Service Module Integration #40 
* [x] Payload preparation #35 #37 
* [x] Payload Train Integration #46 
* [x] Launch Window Arrangement #39 
* [x] Recovery Plan
* [x] Prepare launch equipment
