### ISSUE TITLE
Camera Payload

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#35]
* [x] Modify Secondary Camera
* [x] Prepare CAM-PL Pod #48 
* [x] Integrate CAM-PL
* ~~EMC Test with GPS-GSM Tracker #38~~
* [x] CAM-PL Thermal Test #36

**Comment by Bgoczan** [comment]
CAM1 completely malfunctioned and has been removed from the scope of the mission
