### ISSUE TITLE
Experimental GPS-GSM Tracker Payload

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#37]
* [x] Enhance GSM Antenna placement
* [x] Add RSSI information
* ~~EMC Test with CAM-PL #38~~
* [x] Connect OpenLog HW with UPRA-LOGGER FW
* [x] Upgrade LDO for higher current consumption

**Comment by Bgoczan** [comment]
Prepared for final integration
