### ISSUE TITLE
GS-TS Preparation

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#42]
* [ ] HW-SW integration of Universal GND #47 
* [ ] Predictor integration to Universal GND
* [ ] Assembly and test Secondary GND Antenna #43 
* [ ] Preparation of SDR Based Secondary GS-TS #44 
* [ ] GND.RF69x MODEM Firmware Check #49

**Comment by Bgoczan** [comment]
All issues will be moved to another scope
