### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#51]
* [ ] Flight Planning #52 
* [ ] Procurement #54
* [x] STRU Manufacture
* [x] Flight Computer Smoke Test #56
* [ ] UPRA-CAM.328 Full Test #57 
* [x] Control Camera Smoke Test #60
* [x] Backup GPS Tracker #53 
* [x] Radar Reflector
* [x] UGND HW-SW Integration
* [x] Avionics Integration (Service Module)
* [x] Full System Integration 
* [x] Ground Station Arrangements
