### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#66]
* [x] Flight Planning #67 
* [x] Procurement  
* [x] Flight Computer Smoke Test #68 
* [x] Control Camera Smoke Test 
* [x] Backup GPS Tracker Smoke Test
* [x] GND Preparations
* [x] Ground Station Arrangements
* [x] Avionics Integration (Service Module)
* [x] Backup GPS Integration
* [x] Control Camera Integration
* [x] Payload Integration
* [x] Full System Integration
