### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#77]
-------------------
* [x] Flight Planning #78 
* [x] Procurement 
* [x] Flight Computer Smoke Test #79
* [ ] Control Camera Smoke Test 
* [x] TOMI Smoke Test @ksstms 
* [x] GND Preparations
* [ ] Ground Station Arrangements
* [x] Avionics Integration (Service Module)
* [x] TOMI Integration @ksstms 
* [x] Control Camera Integration
* [x] Payload Integration
* [x] Full System Integration
