### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#88]
* [x] Flight Planning #87 
* [ ] Procurement  #90
* [x] Flight Computer Smoke Test #86 
* [x] Control Camera Smoke Test 
* [x] Backup GPS Tracker Smoke Test
* [x] GND Preparations
* [x] Ground Station Arrangements
* [x] Avionics Integration (Service Module)
* [x] TOMI Integration
* [x] Control Camera Integration
* [x] Payload Integration
* [x] Full System Integration
