### ISSUE TITLE
Flight Preparations

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-Flights#95]
* [x] Flight Planning 
* [x] Procurement 
* [x] Flight Computer Smoke Test 
* [x] Control Camera Smoke Test 
* [x] Backup GPS Tracker Smoke Test
* [x] GND Preparations
* [x] Ground Station Arrangements
* [x] Maintenance and Repairs
* [x] Avionics Integration (Service Module)
* [x] TOMI Integration
* [x] Control Camera Integration
* [x] Payload Integration
* [x] Full System Integration 
* [x] Launch Preparations #108 
* [x] Recovery Preparations #109
